// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfouysDbxNUu5G0ueIAq-M82EE8RSdY1I',
    appId: '1:935139855472:web:a99c17552f6f4f2914f8b5',
    databaseURL: "https://smart-cradle-system-3e551-default-rtdb.europe-west1.firebasedatabase.app",
    messagingSenderId: '935139855472',
    projectId: 'smart-cradle-system-3e551',
    authDomain: 'smart-cradle-system-3e551.firebaseapp.com',
    storageBucket: 'smart-cradle-system-3e551.appspot.com',
    measurementId: 'G-WMXNYGW1J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5p1ZglXSMZYZlQqGYvIb3uegFjsSTCGs',
    appId: '1:935139855472:android:4d28d64969263ad214f8b5',
    messagingSenderId: '935139855472',
    projectId: 'smart-cradle-system-3e551',
    storageBucket: 'smart-cradle-system-3e551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5n-MPSDN1AictVexDU597spGFjLg7Fk',
    appId: '1:935139855472:ios:5300c1735093a3fc14f8b5',
    messagingSenderId: '935139855472',
    projectId: 'smart-cradle-system-3e551',
    storageBucket: 'smart-cradle-system-3e551.appspot.com',
    iosBundleId: 'com.example.smartCradleInfantsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-5n-MPSDN1AictVexDU597spGFjLg7Fk',
    appId: '1:935139855472:ios:5300c1735093a3fc14f8b5',
    messagingSenderId: '935139855472',
    projectId: 'smart-cradle-system-3e551',
    storageBucket: 'smart-cradle-system-3e551.appspot.com',
    iosBundleId: 'com.example.smartCradleInfantsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfouysDbxNUu5G0ueIAq-M82EE8RSdY1I',
    appId: '1:935139855472:web:133fc38ddcf5899a14f8b5',
    databaseURL: "https://smart-cradle-system-3e551-default-rtdb.europe-west1.firebasedatabase.app",
    messagingSenderId: '935139855472',
    projectId: 'smart-cradle-system-3e551',
    authDomain: 'smart-cradle-system-3e551.firebaseapp.com',
    storageBucket: 'smart-cradle-system-3e551.appspot.com',
    measurementId: 'G-DF92LWB5NQ',
  );
}
